### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by MadeOfMagicAndWires** [mt-empty/shortcut-c-client#1]
Hi there,

I know this project is still very early days, but I made a PKGBUILD ([preview can be viewed here](https://github.com/MadeOfMagicAndWires/AUR/tree/shortcut)).
Currently though, this project is missing a software license which makes it unclear on how this software can be shared.  

So I've come here to:
1) ask for permission to publish the PKGBUILD onto the [AUR](https://aur.archlinux.org), with which your software can be packaged and installed through the `pacman` package manager.

2) Encourage you to [choose a license](https://choosealicense.com/) to let people under what circumstances they can use, modify, and distribute this software.   
This is especially relevant for [shortcut-pages](https://github.com/mt-empty/shortcut-pages) as contributions will automatically be subject of the same license.

**Comment by mt-empty** [comment]
Hi

The software currently has some [bugs](https://github.com/mt-empty/shortcut-c-client/issues?q=is%3Aissue+is%3Aopen+label%3Abug), which need to be fixed before it can be published.

If you are comfortable with C, please open a pull request.

1. You have my permission to publish it 

2. Done.

**Comment by MadeOfMagicAndWires** [comment]
Cheers!

I might take a look at it later if I find some time, but it's been a while since I've written C.
